### ISSUE TITLE
Does not work with Tempsgraph Plugin

### ISSUE THREAD

**Issue by ThorstenWirth** [jneilliii/OctoPrint-CustomBackground#2]
Finally a way to replace that rather ugly mascot.
Only issue: It is incompatible with the Tempsgraph Plugin
http://plugins.octoprint.org/plugins/tempsgraph/

**Comment by jneilliii** [comment]
Thanks for the heads up.  I don't use that plugin, but will see what is causing it to not work.

**Comment by jneilliii** [comment]
I took a quick look at the TempsGraph plugin and unfortunately, I'm not sure if I'll be able to make a change that will allow them to work together because it's using the plotly library and removes the default temp_graph div that I'm applying the background to.  I'm not that familiar with Plotly, so you might get a quicker fix posting an issue on that plugins github.

**Comment by jneilliii** [comment]
Looks like an option for custom backgrounds were added to the TempsGraphPlugin, thanks @Bodagous.
